tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v2c_get.py::test_v2_get_legacy_object PASSED [ 60%]
tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v2c_next.py::test_v2_next PASSED [ 62%]
tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v2c_set.py::test_v2_set PASSED [ 63%]
tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v3_usm_none_none.py::test_usm_no_auth_no_priv PASSED [ 65%]
tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v3_usm_none_none.py::test_usm_no_auth_no_priv_wrong_user PASSED [ 66%]
tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v3_usm_sha_aes128.py::test_usm_sha_aes128 PASSED [ 68%]
tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v3_usm_sha_aes128.py::test_usm_sha_aes128_wrong_auth PASSED [ 69%]
tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v3_usm_sha_aes128.py::test_usm_sha_aes128_wrong_priv PASSED [ 71%]
tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v3_usm_sha_aes128.py::test_usm_sha_aes128_wrong_user PASSED [ 72%]
tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v3_usm_sha_aes256.py::test_usm_sha_aes256 PASSED [ 74%]
tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v3_usm_sha_aes256.py::test_usm_sha_aes256_wrong_auth FAILED [ 75%]
tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v3_usm_sha_aes256.py::test_usm_sha_aes256_wrong_user PASSED [ 77%]
tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v3_usm_sha_none.py::test_usm_sha_none PASSED [ 78%]
tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v3_usm_sha_none.py::test_usm_sha_none_wrong_auth PASSED [ 80%]
tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v3_usm_sha_none.py::test_usm_sha_none_wrong_user PASSED [ 81%]
tests/proto/test_named_bits.py::test_prettyIn_list_valid PASSED          [ 83%]
tests/proto/test_named_bits.py::test_prettyIn_list_multiple_valid PASSED [ 84%]
tests/proto/test_named_bits.py::test_prettyIn_list_invalid PASSED        [ 86%]
tests/proto/test_named_bits.py::test_prettyIn_multiple_octets PASSED     [ 87%]
tests/proto/test_named_bits.py::test_prettyOut_valid PASSED              [ 89%]
tests/proto/test_named_bits.py::test_prettyOut_invalid PASSED            [ 90%]

tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v2c_get.py::test_v2_get_no_access_object
tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v2c_get.py::test_v2_get_no_access_object
tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v2c_get.py::test_v2_get_legacy_object
tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v2c_get.py::test_v2_get_legacy_object
tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v2c_get.py::test_v2_get_no_access_object
tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v2c_get.py::test_v2_get_no_access_object
tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v2c_get.py::test_v2_get_no_access_object
tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v2c_get.py::test_v2_get_legacy_object
tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v2c_get.py::test_v2_get_legacy_object
tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v2c_get.py::test_v2_get_legacy_object
tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v2c_get.py::test_v2_get_legacy_object
  /usr/src/RPM/BUILD/python3-module-pysnmp-7.1.17/tests/agent_context.py:92: DeprecationWarning: importSymbols is deprecated. Please use import_symbols instead.
  /usr/src/RPM/BUILD/python3-module-pysnmp-7.1.17/tests/agent_context.py:92: DeprecationWarning: importSymbols is deprecated. Please use import_symbols instead.
  /usr/src/RPM/BUILD/python3-module-pysnmp-7.1.17/tests/agent_context.py:92: DeprecationWarning: importSymbols is deprecated. Please use import_symbols instead.
  /usr/src/RPM/BUILD/python3-module-pysnmp-7.1.17/tests/agent_context.py:92: DeprecationWarning: importSymbols is deprecated. Please use import_symbols instead.
    ) = mibBuilder.importSymbols(
    ) = mibBuilder.importSymbols(
    ) = mibBuilder.importSymbols(
    ) = mibBuilder.importSymbols(




-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
=========================== short test summary info ============================
=========================== short test summary info ============================
=========================== short test summary info ============================
FAILED tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v3_usm_sha_aes256.py::test_usm_sha_aes256_wrong_auth
FAILED tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v3_usm_sha_aes256.py::test_usm_sha_aes256_wrong_auth
FAILED tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v3_usm_sha_aes256.py::test_usm_sha_aes256_wrong_auth
FAILED tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v3_usm_sha_aes256.py::test_usm_sha_aes256_wrong_auth
=========== 1 failed, 65 passed, 34943 warnings in 238.68s (0:03:58) ===========
=========== 1 failed, 65 passed, 34943 warnings in 238.68s (0:03:58) ===========
=========== 1 failed, 65 passed, 34943 warnings in 238.68s (0:03:58) ===========
=========== 1 failed, 65 passed, 34943 warnings in 238.68s (0:03:58) ===========
INFO     : Command's result: FAILURE
INFO     : Command's result: FAILURE
INFO     : Command's result: FAILURE
INFO     : Command's result: FAILURE
INFO     : Command's error: Command '['python3', '-m', 'pytest', '-vra', '--ignore', 'tests/smi/manager/test_mib-tree-inspection.py', '--ignore', 'tests/smi/manager/test_configure-mib-viewer-and-resolve-pdu-varbinds.py', '--ignore', 'tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v2c_bulkwalk.py', '--ignore', 'tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v1_get.py', '--ignore', 'tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v2c_bulk.py', '--ignore', 'tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v2c_bulkwalk.py', '--ignore', 'tests/hlapi/v3arch/asyncio/agent/ntforg/test_default-v1-trap.py', '--ignore', 'tests/hlapi/v3arch/asyncio/manager/cmdgen/test_custom_asn1_mib_search_path.py', '--ignore', 'tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v1_get.py', '--ignore', 'tests/hlapi/v3arch/asyncio/agent/ntforg/test_v3-trap.py', '--ignore', 'tests/smi/manager/test_convert-between-pdu-varbinds-and-mib-objects.py']' returned non-zero exit status 1.
INFO     : Command's error: Command '['python3', '-m', 'pytest', '-vra', '--ignore', 'tests/smi/manager/test_mib-tree-inspection.py', '--ignore', 'tests/smi/manager/test_configure-mib-viewer-and-resolve-pdu-varbinds.py', '--ignore', 'tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v2c_bulkwalk.py', '--ignore', 'tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v1_get.py', '--ignore', 'tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v2c_bulk.py', '--ignore', 'tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v2c_bulkwalk.py', '--ignore', 'tests/hlapi/v3arch/asyncio/agent/ntforg/test_default-v1-trap.py', '--ignore', 'tests/hlapi/v3arch/asyncio/manager/cmdgen/test_custom_asn1_mib_search_path.py', '--ignore', 'tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v1_get.py', '--ignore', 'tests/hlapi/v3arch/asyncio/agent/ntforg/test_v3-trap.py', '--ignore', 'tests/smi/manager/test_convert-between-pdu-varbinds-and-mib-objects.py']' returned non-zero exit status 1.
INFO     : Command's error: Command '['python3', '-m', 'pytest', '-vra', '--ignore', 'tests/smi/manager/test_mib-tree-inspection.py', '--ignore', 'tests/smi/manager/test_configure-mib-viewer-and-resolve-pdu-varbinds.py', '--ignore', 'tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v2c_bulkwalk.py', '--ignore', 'tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v1_get.py', '--ignore', 'tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v2c_bulk.py', '--ignore', 'tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v2c_bulkwalk.py', '--ignore', 'tests/hlapi/v3arch/asyncio/agent/ntforg/test_default-v1-trap.py', '--ignore', 'tests/hlapi/v3arch/asyncio/manager/cmdgen/test_custom_asn1_mib_search_path.py', '--ignore', 'tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v1_get.py', '--ignore', 'tests/hlapi/v3arch/asyncio/agent/ntforg/test_v3-trap.py', '--ignore', 'tests/smi/manager/test_convert-between-pdu-varbinds-and-mib-objects.py']' returned non-zero exit status 1.
INFO     : Command's error: Command '['python3', '-m', 'pytest', '-vra', '--ignore', 'tests/smi/manager/test_mib-tree-inspection.py', '--ignore', 'tests/smi/manager/test_configure-mib-viewer-and-resolve-pdu-varbinds.py', '--ignore', 'tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v2c_bulkwalk.py', '--ignore', 'tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v1_get.py', '--ignore', 'tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v2c_bulk.py', '--ignore', 'tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v2c_bulkwalk.py', '--ignore', 'tests/hlapi/v3arch/asyncio/agent/ntforg/test_default-v1-trap.py', '--ignore', 'tests/hlapi/v3arch/asyncio/manager/cmdgen/test_custom_asn1_mib_search_path.py', '--ignore', 'tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v1_get.py', '--ignore', 'tests/hlapi/v3arch/asyncio/agent/ntforg/test_v3-trap.py', '--ignore', 'tests/smi/manager/test_convert-between-pdu-varbinds-and-mib-objects.py']' returned non-zero exit status 1.
INFO     : Command's error: Command '['python3', '-m', 'pytest', '-vra', '--ignore', 'tests/smi/manager/test_mib-tree-inspection.py', '--ignore', 'tests/smi/manager/test_configure-mib-viewer-and-resolve-pdu-varbinds.py', '--ignore', 'tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v2c_bulkwalk.py', '--ignore', 'tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v1_get.py', '--ignore', 'tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v2c_bulk.py', '--ignore', 'tests/hlapi/v1arch/asyncio/manager/cmdgen/test_v1arch_v2c_bulkwalk.py', '--ignore', 'tests/hlapi/v3arch/asyncio/agent/ntforg/test_default-v1-trap.py', '--ignore', 'tests/hlapi/v3arch/asyncio/manager/cmdgen/test_custom_asn1_mib_search_path.py', '--ignore', 'tests/hlapi/v3arch/asyncio/manager/cmdgen/test_v1_get.py', '--ignore', 'tests/hlapi/v3arch/asyncio/agent/ntforg/test_v3-trap.py', '--ignore', 'tests/smi/manager/test_convert-between-pdu-varbinds-and-mib-objects.py']' returned non-zero exit status 1.
error: Bad exit status from /usr/src/tmp/rpm-tmp.11456 (%check)
error: Bad exit status from /usr/src/tmp/rpm-tmp.11456 (%check)
error: Bad exit status from /usr/src/tmp/rpm-tmp.11456 (%check)
error: Bad exit status from /usr/src/tmp/rpm-tmp.11456 (%check)
error: Bad exit status from /usr/src/tmp/rpm-tmp.11456 (%check)










RPM build errors:
RPM build errors:
RPM build errors:
RPM build errors:
RPM build errors:
    File /usr/src/RPM/SOURCES/python3-module-pysnmp-7.1.17-alt.patch is smaller than 8 bytes
    File /usr/src/RPM/SOURCES/python3-module-pysnmp-7.1.17-alt.patch is smaller than 8 bytes
    File /usr/src/RPM/SOURCES/python3-module-pysnmp-7.1.17-alt.patch is smaller than 8 bytes
    File /usr/src/RPM/SOURCES/python3-module-pysnmp-7.1.17-alt.patch is smaller than 8 bytes
    File /usr/src/RPM/SOURCES/python3-module-pysnmp-7.1.17-alt.patch is smaller than 8 bytes
    Bad exit status from /usr/src/tmp/rpm-tmp.11456 (%check)
    Bad exit status from /usr/src/tmp/rpm-tmp.11456 (%check)
    Bad exit status from /usr/src/tmp/rpm-tmp.11456 (%check)
    Bad exit status from /usr/src/tmp/rpm-tmp.11456 (%check)
    Bad exit status from /usr/src/tmp/rpm-tmp.11456 (%check)
Command exited with non-zero status 1
Command exited with non-zero status 1
Command exited with non-zero status 1
Command exited with non-zero status 1
Command exited with non-zero status 1
50.85user 2.64system 4:06.04elapsed 21%CPU (0avgtext+0avgdata 100644maxresident)k
50.85user 2.64system 4:06.04elapsed 21%CPU (0avgtext+0avgdata 100644maxresident)k
50.85user 2.64system 4:06.04elapsed 21%CPU (0avgtext+0avgdata 100644maxresident)k
50.85user 2.64system 4:06.04elapsed 21%CPU (0avgtext+0avgdata 100644maxresident)k
0inputs+0outputs (0major+303116minor)pagefaults 0swaps
0inputs+0outputs (0major+303116minor)pagefaults 0swaps
0inputs+0outputs (0major+303116minor)pagefaults 0swaps
hsh-rebuild: rebuild of `python3-module-pysnmp-7.1.17-alt1.src.rpm' failed.
hsh-rebuild: rebuild of `python3-module-pysnmp-7.1.17-alt1.src.rpm' failed.
hsh-rebuild: rebuild of `python3-module-pysnmp-7.1.17-alt1.src.rpm' failed.
Command exited with non-zero status 1
Command exited with non-zero status 1
8.17user 3.10system 4:28.12elapsed 4%CPU (0avgtext+0avgdata 141920maxresident)k
1048inputs+0outputs (0major+292788minor)pagefaults 0swaps
